version: '3'

silent: true

tasks:

  mt:
    desc: Runs the combinations generator for all commands of MultiTest
    cmds:
      - cmd: erlc combinations.erl
      - cmd: erl -noshell -s combinations mt -s init stop

  mt-build:
    desc: Runs the combinations generator for build commands of MultiTest
    cmds:
      - cmd: erlc combinations.erl
      - cmd: erl -noshell -s combinations mt_build -s init stop

  mt-test:
    desc: Runs the combinations generator for test commands of MultiTest
    cmds:
      - cmd: erlc combinations.erl
      - cmd: erl -noshell -s combinations mt_test -s init stop

  mt-clippy:
    desc: Runs the combinations generator for clippy commands of MultiTest
    cmds:
      - cmd: erlc combinations.erl
      - cmd: erl -noshell -s combinations mt_clippy -s init stop
